### ISSUE TITLE
The current build on ubuntu 22.04 fails with "error: invalid conversion from ‘void (*)(int, void*)’ to ‘tii_data_t’"

### ISSUE THREAD

**Issue by hb9fxq** [f4exb/sdrangel#1623]
The current build on Ubuntu 22.04 fails with

```
/opt/build/sdrangel/plugins/channelrx/demoddab/dabdemodsink.cpp:522:30: error: invalid conversion from ‘void (*)(int, void*)’ to ‘tii_data_t’ {aka ‘void (*)(int)’} [-fpermissive]
  522 |     m_api.tii_data_Handler = tiiDataHandler;
      |                              ^~~~~~~~~~~~~~
      |                              |
      |                              void (*)(int, void*)
```

**Comment by srcejon** [comment]
Please do a git update and rebuild the DAB library.
