### ISSUE TITLE
Error while compiling for linux

### ISSUE THREAD

**Issue by fabiodame** [f4exb/sdrangel#985]
I can't compile in Ubuntu 21.10, I'm following this instruction https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux
Am i missing something?
The error I've got is:

/opt/build/sdrangel/sdrbase/util/httpdownloadmanager.cpp: In static member function ‘static qint64 HttpDownloadManager::fileAgeInDays(const QString&)’:
/opt/build/sdrangel/sdrbase/util/httpdownloadmanager.cpp:47:35: error: ‘class QFile’ has no member named ‘fileTime’; did you mean ‘fileName’?
   47 |         QDateTime modified = file.fileTime(QFileDevice::FileModificationTime);
      |                                   ^~~~~~~~
      |                                   fileName
/opt/build/sdrangel/sdrbase/util/httpdownloadmanager.cpp:47:57: error: ‘FileModificationTime’ is not a member of ‘QFileDevice’
   47 |         QDateTime modified = file.fileTime(QFileDevice::FileModificationTime);
      |                                                         ^~~~~~~~~~~~~~~~~~~~
[ 25%] Building CXX object sdrbase/CMakeFiles/sdrbase.dir/util/prettyprint.cpp.o
make[2]: *** [sdrbase/CMakeFiles/sdrbase.dir/build.make:1748: sdrbase/CMakeFiles/sdrbase.dir/util/httpdownloadmanager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:4502: sdrbase/CMakeFiles/sdrbase.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

I think i have the wrong qt version,
when i run "qmake --version" it says "QMake version 3.1      Using Qt version 5.9.7"
but if i try to install the "general prerequisite you should have the following packages installed" i get:
"libqt5charts5-dev is already the newest version (5.15.2-2)" and similar, seems like i have the latest libqt5

**Comment by ChiefGokhlayeh** [comment]
Do you, by chance, have multiple installs of Qt/`qmake`? Make sure to use the one shipped with >=Qt5.12.

Alternatively, going by [this answer on StackExchange](https://unix.stackexchange.com/questions/116254/how-do-i-change-which-version-of-qt-is-used-for-qmake), you might wanna try pointing environment variable `QTDIR` to your qt5.12 directory.
