### ISSUE TITLE
gcc 15.2.1 error

### ISSUE THREAD

**Issue by garyemiller** [f4exb/sdrangel#2592]
I'm trying to build on Gentoo unstable, with gcc 15.2.1 and qt6.  gcc 15 is pickier than before.  Using this build procedure:

````
cd /opt/build/sdrangel
cmake --preset default-qt6
cd build-qt6
make -j 3 install
````

Don't laugh, I get  52% done, before it errors out on a warning that has likely been there a while:

````
[ 52%] Building CXX object pluginssrv/channeltx/modm17/CMakeFiles/modm17srv.dir/m17moddecimator.cpp.o
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp: In member function ‘AVFrame* TSGenerator::load_image_to_yuv(const char*, int, int)’:
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:130:19: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  130 |     av_init_packet(&pkt);
      |     ~~~~~~~~~~~~~~^~~~~~
In file included from /usr/include/libavcodec/avcodec.h:44,
                 from /mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:20:
/usr/include/libavcodec/packet.h:683:6: note: declared here
  683 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp: In member function ‘int TSGenerator::setup_ts_context(AVFormatContext**, AVCodecContext*)’:
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:309:47: error: invalid conversion from ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} to ‘int (*)(void*, const uint8_t*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} [-fpermissive]
  309 |     AVIOContext* avio_ctx = avio_alloc_context(
      |                             ~~~~~~~~~~~~~~~~~~^
      |                                               |
      |                                               int (*)(void*, uint8_t*, int) {aka int (*)(void*, unsigned char*, int)}
  310 |         iobuf, 32768,  // Buffer size
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
  311 |         1,             // Write mode
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
  312 |         &ts_buffer,    // Your std::vector<uint8_t>*
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  313 |         read_packet_cb, // Read callback (unused)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  314 |         write_packet_cb, // Write callback → your memory buffer
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  315 |         seek_cb         // Seek callback (unused)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  316 |     );
      |     ~                                          
In file included from /usr/include/libavformat/avformat.h:319,
                 from /mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:21:
/usr/include/libavformat/avio.h:404:25: note: initializing argument 6 of ‘AVIOContext* avio_alloc_context(unsigned char*, int, int, void*, int (*)(void*, uint8_t*, int), int (*)(void*, const uint8_t*, int), int64_t (*)(void*, int64_t, int))’
  404 |                   int (*write_packet)(void *opaque, const uint8_t *buf, int buf_size),
      |                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp: In member function ‘void TSGenerator::encode_frame_to_ts(AVFormatContext*, AVCodecContext*, AVFrame*, int)’:
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::pts’ [-Wmissing-field-initializers]
  342 |     AVPacket pkt = {nullptr};
      |                            ^
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::dts’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::data’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::size’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::stream_index’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::flags’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::side_data’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::side_data_elems’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::duration’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::pos’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::opaque’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::opaque_ref’ [-Wmissing-field-initializers]
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:342:28: warning: missing initializer for member ‘AVPacket::time_base’ [-Wmissing-field-initializers]
[ 52%] Building CXX object pluginssrv/channeltx/modm17/CMakeFiles/modm17srv.dir/m17modax25.cpp.o
[ 52%] Building CXX object pluginssrv/channeltx/moddatv/CMakeFiles/moddatvsrv.dir/dvb-s2/dvb2_ldpc_encode.cpp.o
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp: In member function ‘void TSGenerator::generate_still_image_ts(const char*, int, bool, int)’:
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:69:26: warning: ignoring return value of ‘int avformat_write_header(AVFormatContext*, AVDictionary**)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   69 |     avformat_write_header(oc, nullptr);
      |     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
make[2]: *** [pluginssrv/channeltx/moddatv/CMakeFiles/moddatvsrv.dir/build.make:209: pluginssrv/channeltx/moddatv/CMakeFiles/moddatvsrv.dir/tsgenerator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 52%] Building CXX object pluginssrv/channeltx/modm17/CMakeFiles/modm17srv.dir/m17modplugin.cpp.o
make[1]: *** [CMakeFiles/Makefile2:21824: pluginssrv/channeltx/moddatv/CMakeFiles/moddatvsrv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 52%] Building CXX object pluginssrv/channeltx/modm17/CMakeFiles/modm17srv.dir/m17modsettings.cpp.o
[ 52%] Building CXX object pluginssrv/channeltx/modm17/CMakeFiles/modm17srv.dir/m17modwebapiadapter.cpp.o
[ 52%] Linking CXX shared module ../../../lib/pluginssrv/libmodm17srv.so
[ 52%] Built target modm17srv
make: *** [Makefile:156: all] Error 2
````

The error, hidden in the earnings, is simple:

````
/mnt/backup/src/Radio/sdrangel/plugins/channeltx/moddatv/tsgenerator.cpp:309:47: error: invalid conversion from ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} to ‘int (*)(void*, const uint8_t*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} [-fpermissive]
  309 |     AVIOContext* avio_ctx = avio_alloc_context(
      |                             ~~~~~~~~~~~~~~~~~~^
      |                                               |
      |                                               int (*)(void*, uint8_t*, int) {aka int (*)(void*, unsigned char*, int)}
  310 |         iobuf, 32768,  // Buffer size
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
  311 |         1,             // Write mode
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
  312 |         &ts_buffer,    // Your std::vector<uint8_t>*
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  313 |         read_packet_cb, // Read callback (unused)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  314 |         write_packet_cb, // Write callback → your memory buffer
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  315 |         seek_cb         // Seek callback (unused)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  316 |     );
      |     ~                                          
````

This function:

int TSGenerator::write_packet_cb(void* opaque, uint8_t* buf, int buf_size)

S/b:

int TSGenerator::write_packet_cb(void* opaque, const uint8_t* buf, int buf_size)

Note the added const.

Easy fix.

**Comment by f4exb** [comment]
This is an issue with the version of libavformat which is not the same across systems and changed between versions 60 and 61. This should be fixed on the master branch please pull the latest commit.

**Comment by garyemiller** [comment]
Thanks for the fast response.  This issue is indeed resolved.  Now I get to 57%

````
[ 57%] Building CXX object pluginssrv/samplesource/rtlsdr/CMakeFiles/inputrtlsdrsrv.dir/rtlsdrinput.cpp.o
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp: In member function ‘bool SDRPlayV3Input::applySettings(const SDRPlayV3Settings&, const QList<QString>&, bool, bool)’:
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:524:18: error: ‘SDRPLAY_RSP1B_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSP1_ID’?
  524 |             case SDRPLAY_RSP1B_ID:
      |                  ^~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSP1_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:541:18: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
  541 |             case SDRPLAY_RSPdxR2_ID:
      |                  ^~~~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSPdx_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:587:18: error: ‘SDRPLAY_RSP1B_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSP1_ID’?
  587 |             case SDRPLAY_RSP1B_ID:
      |                  ^~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSP1_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:603:18: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
  603 |             case SDRPLAY_RSPdxR2_ID:
      |                  ^~~~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSPdx_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:625:18: error: ‘SDRPLAY_RSP1B_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSP1_ID’?
  625 |             case SDRPLAY_RSP1B_ID:
      |                  ^~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSP1_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:637:18: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
  637 |             case SDRPLAY_RSPdxR2_ID:
      |                  ^~~~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSPdx_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:671:18: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
  671 |             case SDRPLAY_RSPdxR2_ID:
      |                  ^~~~~~~~~~~~~~~~~~
      |                  SDRPLAY_RSPdx_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp: In member function ‘void SDRPlayV3Input::webapiFormatDeviceReport(SWGSDRangel::SWGDeviceReport&)’:
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:1009:10: error: ‘SDRPLAY_RSP1B_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSP1_ID’?
 1009 |     case SDRPLAY_RSP1B_ID:
      |          ^~~~~~~~~~~~~~~~
      |          SDRPLAY_RSP1_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:1021:10: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
 1021 |     case SDRPLAY_RSPdxR2_ID:
      |          ^~~~~~~~~~~~~~~~~~
      |          SDRPLAY_RSPdx_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp: In static member function ‘static const int* SDRPlayV3LNA::getAttenuations(int, qint64)’:
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:1422:10: error: ‘SDRPLAY_RSP1B_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSP1_ID’?
 1422 |     case SDRPLAY_RSP1B_ID:
      |          ^~~~~~~~~~~~~~~~
      |          SDRPLAY_RSP1_ID
/mnt/backup/src/Radio/sdrangel/plugins/samplesource/sdrplayv3/sdrplayv3input.cpp:1456:10: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
 1456 |     case SDRPLAY_RSPdxR2_ID:
      |          ^~~~~~~~~~~~~~~~~~
      |          SDRPLAY_RSPdx_ID
make[2]: *** [pluginssrv/samplesource/sdrplayv3/CMakeFiles/inputsdrplayv3srv.dir/build.make:111: pluginssrv/samplesource/sdrplayv3/CMakeFiles/inputsdrplayv3srv.dir/sdrplayv3input.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:24387: pluginssrv/samplesource/sdrplayv3/CMakeFiles/inputsdrplayv3srv.dir/all] Error 2
````

My sdrplay is version 3.0.7.  Gentoo allows me to downgrade to 2.13.1 if that would help.  Or uninstall it.

**Comment by talkingerbil** [comment]
Did you use srcejon's git repo to install those drivers? He's a few versions ahead of the gentoo repo (even testing).
Builds just fine on my gentoo install.

**Comment by srcejon** [comment]
SDRplay API 3.15 is needed.

https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux

        cd /opt/build
        git clone https://github.com/srcejon/sdrplayapi.git
        cd sdrplayapi
        sudo ./install_lib.sh

**Comment by garyemiller** [comment]
> Did you use srcejon's git repo to install those drivers?

No.  I just used the sdrplay in the main Gentoo repo.  But I do not have that hardware, so I just removed. sdrplay.  Then it built just fine for me.  A few optional packages that I will get to later.

So my build issues are resolved.  Thanks!

**Comment by garyemiller** [comment]
I think I have all the optional packages that Gentoo has for SDRangel installed.    Makes me wonder if there is an alternate Gentoo repo for things like hamlib.

It builds and runs.  Thanks!  Now I have a big learning curve.
